# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-07 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_task', models.TextField(max_length=400)),
                ('log_sol', models.CharField(blank=True, max_length=100, null=True)),
                ('log_answer', models.CharField(blank=True, editable=False, max_length=100, null=True)),
            ],
        ),
    ]
