# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-14 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logica', '0005_auto_20161214_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmodel',
            name='log_answer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
