# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-27 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logica', '0013_auto_20161227_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmodel',
            name='log_answer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
