# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-14 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Erudmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erud_task', models.TextField(max_length=400)),
                ('erud_sol', models.CharField(choices=[('a', '\u0432\u0430\u0440\u0438\u0430\u043d\u0442 a'), ('b', '\u0432\u0430\u0440\u0438\u0430\u043d\u0442 b'), ('c', '\u0432\u0430\u0440\u0438\u0430\u043d\u0442 c'), ('d', '\u043f\u0440\u043e\u043f\u0443\u0441\u0442\u0438\u0442\u044c \u0432\u043e\u043f\u0440\u043e\u0441')], default=None, max_length=100, null=True)),
                ('erud_answer', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
