# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-14 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=50)),
                ('sol', models.IntegerField()),
                ('answer', models.IntegerField(editable=False)),
                ('check', models.CharField(max_length=20)),
            ],
        ),
    ]
