# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-14 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='check',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='solution',
            name='sol',
            field=models.IntegerField(blank=True),
        ),
    ]
