# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-14 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alg', '0002_auto_20161114_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='answer',
            field=models.IntegerField(blank=True, editable=False),
        ),
    ]
