# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-14 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alg', '0003_auto_20161114_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='answer',
            field=models.IntegerField(blank=True, default=None, editable=False),
        ),
        migrations.AlterField(
            model_name='solution',
            name='check',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='solution',
            name='sol',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
