# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-17 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alg', '0005_auto_20161114_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='task',
            field=models.IntegerField(),
        ),
    ]
