# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-21 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alg', '0006_auto_20161117_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='task',
            field=models.CharField(max_length=100),
        ),
    ]
