# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-23 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alg', '0007_auto_20161121_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='check',
        ),
    ]
