# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-02 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='humormodel',
            old_name='erud_answer',
            new_name='humor_answer',
        ),
        migrations.RenameField(
            model_name='humormodel',
            old_name='erud_sol',
            new_name='humor_sol',
        ),
        migrations.RenameField(
            model_name='humormodel',
            old_name='erud_task',
            new_name='humor_task',
        ),
        migrations.AddField(
            model_name='humormodel',
            name='humor_exp',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
